#!/bin/bash

function check_configs() {
    local src_dir="$1"
    local num_count=0
    local num_passed=0
    local num_total=$(count_items "$src_dir" "f")
    local response_check=
    echo "Processing $num_total file(s) in $src_dir directory."
    local port_socks=10000
    local port_http=13000
    for file in "$src_dir"/*; do
        ((num_count++))
        local new_port_socks=$((port_socks + num_count))
        local new_port_http=$((port_http + num_count))
        sed -i -e "13s/[0-9]\+/$new_port_socks/" -e "29s/[0-9]\+/$new_port_http/" "$file"
        {
            IFS=',' read -r pid <<<"$(xray_connection_check "$file" true "$new_port_http")"
            kill_process "$pid" >/dev/null 2>&1
        } &
        progress_bar "$num_count" "$num_total"
    done
    wait
    echo -ne "\n"
}

function xray_connection_check() {
    local file="$1"
    local country="$2"
    local port="$3"
    $xray_app run -c "$file" >/dev/null 2>&1 &
    local pid=$!
    sleep 15
    local attempts=0
    local response_check=false
    while ((attempts < 3)); do
        sleep 2
        local response_curl=$(curl -x http://127.0.0.1:"$port" -s -m 10 https://api.country.is)
        if [[ -n "$response_curl" && $(jq -r '.country' <<<"$response_curl") != "null" ]]; then
            if [[ "$country" == true ]]; then
                sed -i -e "13s/[0-9]\+/10808/" -e "29s/[0-9]\+/10809/" "$file"
                append_country_code_to_filename "$file" "$response_curl"
            fi
            response_check=true
            break
        fi
        ((attempts++))
    done
    echo "$pid"
}

function append_country_code_to_filename() {
    local file="$1"
    local response_curl="$2"
    local filename=$(basename "$file")
    local filedir=$(dirname "$file")
    local pattern="^\[.*\] \[.*\] \[.*\]\.json$"
    if [[ ! $filename =~ $pattern ]]; then
        local country_code=$(jq -r '.country' <<<"$response_curl" | tr '[:upper:]' '[:lower:]')
        if [[ -z "$country_code" ]]; then
            country_code="xx"
        fi
        local filerename=$(sed -E "s/^(\[[^]]+])( \[[^]]+])(.json)$/\[$country_code] \1\2\3/" <<<"$filename")
        mv -f "$file" "$filedir/$filerename"
    fi
}
