name: Main

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 16 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          rm -rf output
          mkdir -p output
          sudo apt-get update
          sudo apt-get install -y jq curl
          chmod +x src/xray/xray
          chmod +x src/bash/fetch
          chmod +x src/bash/check
          chmod +x src/bash/base64

      - name: Run Bash script
        run: |
          ./src/bash/fetch
          ./src/bash/check
          ./src/bash/base64

      - name: Commit and push changes
        run: |
          git config --global user.name 'wuqb2i4f'
          git config --global user.email 'wuqb2i4f@duck.com'
          git add .
          git commit -m "Updated"
          git push
