name: Stage-1

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */1 * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Fetch Repository Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Step 2 - Setup Dependencies
        run: sudo apt-get install -y fdupes

      - name: Step 3 - Fetch Data
        run: src/bash/main fetch

      - name: Step 4 - Commit and Push Changes
        run: src/bash/main gitupdate
